name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Container Apps Build and Deploy
      uses: Azure/container-apps-deploy-action@v2
